"""Core modules - PowerShell executor, mailbox operations, hold analyzer, cost calculator, validator."""

from src.core.powershell_executor import PowerShellExecutor, PowerShellResult, PowerShellError
from src.core.exchange_connection import (
    ExchangeConnection,
    ConnectionState,
    ExchangeConnectionError,
    exchange_session,
)
from src.core.mailbox_service import MailboxService, MailboxServiceError
from src.core.cache_manager import CacheManager
from src.core.hold_analyzer import (
    HoldAnalyzer,
    HoldAnalyzerError,
    HoldType,
    Hold,
    MailboxHoldInfo,
)
from src.core.filter_service import FilterService, FilterCriteria, SortCriteria
from src.core.statistics_service import StatisticsService, SummaryStats
from src.core.export_service import ExportService, ExportError
from src.core.recovery_validator import (
    RecoveryValidator,
    RecoveryValidatorError,
    ValidationResult,
    ValidationIssue,
    ValidationCode,
    ValidationSeverity,
)
from src.core.recovery_service import (
    RecoveryService,
    RecoveryServiceError,
    RecoveryRequest,
    RecoveryResult,
)
from src.core.recovery_wizard import RecoveryWizard, WizardStep, WizardState
from src.core.restore_service import (
    RestoreService,
    RestoreServiceError,
    RestoreRequest,
    RestoreResult,
)
from src.core.operation_monitor import (
    OperationMonitor,
    OperationProgress,
    OperationStatus,
)
from src.core.bulk_operations import (
    BulkOperationManager,
    BulkOperationType,
    BulkItemStatus,
    BulkOperationItem,
    BulkOperationResult,
    BulkOperationConfig,
    BulkCSVHandler,
    BulkCSVError,
    BulkOperationError,
)
from src.core.cost_calculator import (
    CostCalculator,
    CostCalculatorError,
    CostConfig,
    CostReport,
    CostSummary,
    LicenseCost,
    LicenseType,
    MailboxCostInfo,
    DEFAULT_LICENSE_COSTS,
)
from src.core.dashboard_service import (
    DashboardService,
    DashboardServiceError,
    DashboardData,
    ChartData,
    ChartDataPoint,
    ChartType,
    MetricCard,
    CHART_COLORS,
    HOLD_TYPE_COLORS,
    STATUS_COLORS,
    format_currency,
    format_size,
    format_percentage,
    format_number,
    format_date,
    format_duration,
)
from src.core.report_generator import (
    ReportManager,
    ReportFormat,
    ReportType,
    ReportConfig,
    ReportMetadata,
    ReportResult,
    ReportGeneratorError,
    ExcelReportGenerator,
    HTMLReportGenerator,
)

__all__ = [
    "PowerShellExecutor",
    "PowerShellResult",
    "PowerShellError",
    "ExchangeConnection",
    "ConnectionState",
    "ExchangeConnectionError",
    "exchange_session",
    "MailboxService",
    "MailboxServiceError",
    "CacheManager",
    "HoldAnalyzer",
    "HoldAnalyzerError",
    "HoldType",
    "Hold",
    "MailboxHoldInfo",
    "FilterService",
    "FilterCriteria",
    "SortCriteria",
    "StatisticsService",
    "SummaryStats",
    "ExportService",
    "ExportError",
    "RecoveryValidator",
    "RecoveryValidatorError",
    "ValidationResult",
    "ValidationIssue",
    "ValidationCode",
    "ValidationSeverity",
    "RecoveryService",
    "RecoveryServiceError",
    "RecoveryRequest",
    "RecoveryResult",
    "RecoveryWizard",
    "WizardStep",
    "WizardState",
    "RestoreService",
    "RestoreServiceError",
    "RestoreRequest",
    "RestoreResult",
    "OperationMonitor",
    "OperationProgress",
    "OperationStatus",
    "BulkOperationManager",
    "BulkOperationType",
    "BulkItemStatus",
    "BulkOperationItem",
    "BulkOperationResult",
    "BulkOperationConfig",
    "BulkCSVHandler",
    "BulkCSVError",
    "BulkOperationError",
    "CostCalculator",
    "CostCalculatorError",
    "CostConfig",
    "CostReport",
    "CostSummary",
    "LicenseCost",
    "LicenseType",
    "MailboxCostInfo",
    "DEFAULT_LICENSE_COSTS",
    "DashboardService",
    "DashboardServiceError",
    "DashboardData",
    "ChartData",
    "ChartDataPoint",
    "ChartType",
    "MetricCard",
    "CHART_COLORS",
    "HOLD_TYPE_COLORS",
    "STATUS_COLORS",
    "format_currency",
    "format_size",
    "format_percentage",
    "format_number",
    "format_date",
    "format_duration",
    "ReportManager",
    "ReportFormat",
    "ReportType",
    "ReportConfig",
    "ReportMetadata",
    "ReportResult",
    "ReportGeneratorError",
    "ExcelReportGenerator",
    "HTMLReportGenerator",
]
